{% set version = "0.1.0" %}

package:
  name: src 
  version: {{ version }}

source:
  path: ../src
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - cuda-toolkit
    - pybind11
    - cmake
    - make
  host:
    - python
    - pybind11
  run:
    - python
    - Jinja2
    - numpy
    - cuda-toolkit

build:
  number: 0
  noarch: python
  script: |

about:
  home: https://github.com/vbharadwaj-bk/equivariant_spmm
  license: MIT
  summary: 'Accelerated GPU kernels for equivariant deep neural networks.'