{% set version = "0.1.0" %}

package:
  name: openequivariance 
  version: {{ version }}

source:
  path: ..
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python >=3.9
    - cuda-toolkit
    - pybind11
    - cmake
    - make
    - setuptools
  host:
    - python >=3.9 
    - pybind11
    - setuptools
  run:
    - python
    - Jinja2
    - numpy
    - pytorch
    - cuda-toolkit
    - setuptools

build:
  number: 0
  noarch: python

about:
  home: https://github.com/vbharadwaj-bk/OpenEquivariance
  license: MIT
  summary: 'Accelerated GPU kernels for equivariant deep neural networks.'