name: equivariant_spmm_env
channels:
  - conda-forge
  - nvidia
  - pytorch
  - default
dependencies: 
  - python=3.11 

  # Core Function
  - numpy
  - jinja2 
  - pybind11 

  # Reordering CG coefficients
  - pandas

  # plotting 
  - matplotlib
  - seaborn

  # pytorch and e3nn stuff
  - pip 
  - pytorch 
  - pip:
    - e3nn 
    - e3nn_jax
    - cuequivariance
    - cuequivariance-jax
    - cuequivariance-torch
    - cuequivariance-ops-torch-cu12