"""AD primitives for generated preprojected factorized kernels."""

import jax
import jax.numpy as jnp
import numpy as np
from jax.extend import core
from jax.interpreters import ad, batching, mlir

from openequivariance.core.FactorizedComputationSchedule import Input
from openequivariance.jax.ffi_targets import FACTORIZED_TARGET
from openequivariance.jax.extlib import IS_HIP

FACTORIZED_FORWARD = 0
FACTORIZED_BACKWARD = 2


def factorized_forward_jvp_operation(active: tuple[bool, bool, bool]) -> int:
    """Encode the active forward-JVP tangent buffers for the native ABI."""
    return 16 + sum(1 << index for index, value in enumerate(active) if value)


def factorized_backward_jvp_operation(
    active: tuple[bool, bool, bool, bool],
) -> int:
    """Encode the active backward-JVP tangent buffers for the native ABI."""
    mask = sum(1 << index for index, value in enumerate(active) if value)
    if mask == 0:
        raise ValueError("factorized backward JVP requires an active tangent")
    return 32 + mask


def _materialize_symbolic_zero(value):
    """Materialize a symbolic AD zero only after its activity was classified.

    Lowerings omit inactive operands, so callers must not materialize a zero
    merely to satisfy a generated-kernel argument list.
    """
    if ad.is_undefined_primal(value) or type(value) is ad.Zero:
        return jnp.zeros(value.aval.shape, value.aval.dtype)
    return value


def _generated_attrs(schedule, dtype, **source_options):
    """Return FFI attributes generated by the static computation schedule."""
    specialization = schedule.kernel(dtype, is_hip=IS_HIP, **source_options)
    return dict(specialization.ffi_attributes)


def _ffi_lowering(target, operand_indices, *, operation, source_options=None):
    """Lower directly to FFI without recursively tracing the Python impl.

    ``mlir.lower_fun`` is unsuitable here: the implementation constructs an
    ``ffi_call`` whose internal lowering cache can retain the surrounding
    primitive tracer during the nested trace.  Building the FFI custom call
    directly is both simpler and safe for repeated JIT/export traces.
    """
    source_options = source_options or (lambda params: {})

    def lowering(ctx, *operands, schedule, **params):
        attributes = _generated_attrs(
            schedule,
            ctx.avals_in[0].dtype,
            **source_options(params),
        )
        attributes["operation"] = (
            operation(params) if callable(operation) else operation
        )
        rule = jax.ffi.ffi_lowering(target)
        indices = (
            operand_indices(params) if callable(operand_indices) else operand_indices
        )
        selected = tuple(operands[index] for index in indices)
        return rule(
            ctx.replace(avals_in=tuple(ctx.avals_in[index] for index in indices)),
            *selected,
            **attributes,
        )

    return lowering


def _register_generated_lowering(
    primitive, operand_indices, *, operation, source_options=None
):
    """Register the identical generated FFI lowering on both GPU platforms."""
    for platform in ("cuda", "rocm"):
        mlir.register_lowering(
            primitive,
            _ffi_lowering(
                FACTORIZED_TARGET,
                operand_indices,
                operation=operation,
                source_options=source_options,
            ),
            platform=platform,
        )


def _validate(schedule, x, sh, weights, senders, receivers, row_ptr, dout=None):
    e = senders.shape[0]
    if x.ndim != 2 or x.shape[1] != schedule.input_dim:
        raise ValueError(f"x must have shape [N, {schedule.input_dim}]")
    if sh.shape != (e, schedule.edge_dim) or weights.shape != (
        e,
        schedule.weight_numel,
    ):
        raise ValueError("sh/weights must have E rows and schedule feature widths")
    if receivers.shape != senders.shape or senders.dtype != np.dtype(np.int32):
        raise ValueError("senders/receivers must be equal int32 vectors")
    if receivers.dtype != np.dtype(np.int32) or row_ptr.dtype != np.dtype(np.int32):
        raise ValueError("topology must use int32")
    if row_ptr.shape != (x.shape[0] + 1,):
        raise ValueError("receiver row pointer must have shape [N+1]")
    if sh.dtype != x.dtype or weights.dtype != x.dtype:
        raise ValueError("floating operand dtypes must match")
    if dout is not None and (
        dout.shape != (x.shape[0], schedule.output_dim) or dout.dtype != x.dtype
    ):
        raise ValueError("dout shape/dtype mismatch")


dbwd_p = core.Primitive("factorized_projected_q_dbwd")
dbwd_p.multiple_results = True
fwd_jvp_p = core.Primitive("factorized_projected_fwd_jvp")


def _batch_factorized(primitive, value_kinds, result_kinds, tangent_start=None):
    """Flatten a shared-topology batch into one generated convolution call.

    Valid graph blocks are packed before one global padded suffix. Graph-local
    indices are offset before flattening, while invalid endpoints are mapped to
    the single out-of-bounds node index of the flattened batch. This preserves
    receiver order and lets the generated kernels discard padding immediately.
    """

    def rule(args, axes, *, schedule, **params):
        value_count = len(value_kinds)
        topology_axes = axes[value_count:]
        if any(axis is not None for axis in topology_axes):
            raise NotImplementedError(
                "vmap over receiver topology is unsupported. Map X, Y, W, "
                "and derivative arrays while keeping rows and cols static."
            )
        sizes = [
            value.shape[axis]
            for value, axis in zip(args[:value_count], axes[:value_count])
            if axis is not None
        ]
        if not sizes:
            result = primitive.bind(*args, schedule=schedule, **params)
            return result, (0,) * len(result) if primitive.multiple_results else 0
        batch_size = sizes[0]
        if any(size != batch_size for size in sizes[1:]):
            raise ValueError("vmap batch dimensions must have matching sizes")

        def leading_axis(value, axis):
            if axis is None:
                return jnp.broadcast_to(value, (batch_size,) + value.shape)
            return jnp.moveaxis(value, axis, 0)

        active = params.get("active")
        values = []
        for index, (value, axis, kind) in enumerate(
            zip(args[:value_count], axes[:value_count], value_kinds)
        ):
            is_active = (
                tangent_start is None
                or index < tangent_start
                or active[index - tangent_start]
            )
            values.append(value if not is_active else leading_axis(value, axis))

        x = values[0]
        nodes, edges = x.shape[1], args[value_count].shape[0]
        node_offsets = jnp.arange(batch_size, dtype=jnp.int32) * nodes
        senders, receivers, row_ptr = args[value_count:]
        edge_indices = jnp.arange(edges, dtype=jnp.int32)
        valid_count = row_ptr[-1]
        valid_edges = edge_indices < valid_count
        graph_indices = jnp.arange(batch_size, dtype=jnp.int32)[:, None]
        destination = jnp.where(
            valid_edges[None, :],
            graph_indices * valid_count + edge_indices[None, :],
            batch_size * valid_count
            + graph_indices * (edges - valid_count)
            + edge_indices[None, :]
            - valid_count,
        ).reshape(-1)

        def pack_edges(value):
            flat = value.reshape((-1,) + value.shape[2:])
            return jnp.zeros_like(flat).at[destination].set(flat)

        sentinel = jnp.asarray(batch_size * nodes, dtype=jnp.int32)
        senders = pack_edges(
            jnp.where(
                valid_edges[None, :],
                senders[None, :] + node_offsets[:, None],
                sentinel,
            )
        )
        receivers = pack_edges(
            jnp.where(
                valid_edges[None, :],
                receivers[None, :] + node_offsets[:, None],
                sentinel,
            )
        )
        row_offsets = jnp.arange(batch_size, dtype=jnp.int32) * valid_count
        row_ptr = jnp.concatenate(
            (
                (row_offsets[:, None] + row_ptr[None, :-1]).reshape(-1),
                jnp.asarray((batch_size * valid_count,), dtype=jnp.int32),
            )
        )

        flat_values = []
        for index, (value, kind) in enumerate(zip(values, value_kinds)):
            is_active = (
                tangent_start is None
                or index < tangent_start
                or active[index - tangent_start]
            )
            if not is_active:
                flat_values.append(value)
            elif kind == "node":
                flat_values.append(value.reshape(-1, value.shape[-1]))
            else:
                flat_values.append(pack_edges(value))

        result = primitive.bind(
            *flat_values, senders, receivers, row_ptr, schedule=schedule, **params
        )

        def restore(value, kind):
            if kind == "node":
                return value.reshape(batch_size, nodes, value.shape[-1])
            return value[destination].reshape(batch_size, edges, value.shape[-1])

        if primitive.multiple_results:
            return (
                tuple(
                    restore(value, kind) for value, kind in zip(result, result_kinds)
                ),
                (0,) * len(result_kinds),
            )
        return restore(result, result_kinds[0]), 0

    return rule


def _fixed_generated_primitive(
    name, operation, ffi_indices, result_indices, *, dout_index=None
):
    """Create one fixed-arity projected primitive from its native ABI descriptor.

    The descriptor keeps the public primitive name, operation code, result
    shape, and native operand order together. It removes repeated plumbing
    without merging the distinct JAX primitives used by AD and batching rules.
    """
    primitive = core.Primitive(name)
    primitive.multiple_results = isinstance(result_indices, tuple)

    def validate(args, schedule):
        x, sh, weights = args[:3]
        senders, receivers, row_ptr = args[-3:]
        dout = None if dout_index is None else args[dout_index]
        _validate(schedule, x, sh, weights, senders, receivers, row_ptr, dout)

    def specs(args, schedule, array_type):
        if result_indices == "output":
            values = (((args[0].shape[0], schedule.output_dim), args[0].dtype),)
        else:
            indices = (
                result_indices
                if isinstance(result_indices, tuple)
                else (result_indices,)
            )
            values = tuple((args[index].shape, args[index].dtype) for index in indices)
        return tuple(array_type(shape, dtype) for shape, dtype in values)

    def impl(*args, schedule):
        validate(args, schedule)
        attributes = _generated_attrs(schedule, args[0].dtype)
        shapes = specs(args, schedule, jax.ShapeDtypeStruct)
        return jax.ffi.ffi_call(
            FACTORIZED_TARGET, shapes if primitive.multiple_results else shapes[0]
        )(
            *(args[index] for index in ffi_indices),
            operation=operation,
            **attributes,
        )

    def abstract(*args, schedule):
        validate(args, schedule)
        values = specs(args, schedule, jax.core.ShapedArray)
        return values if primitive.multiple_results else values[0]

    primitive.def_impl(impl)
    primitive.def_abstract_eval(abstract)
    _register_generated_lowering(primitive, ffi_indices, operation=operation)
    return primitive


fwd_p = _fixed_generated_primitive(
    "factorized_projected_fwd",
    FACTORIZED_FORWARD,
    (Input.X.value, Input.SH.value, Input.W.value, 3, 5),
    "output",
)
# B_q returns the complete gradient with q=(x, sh, preprojected weights).
bwd_p = _fixed_generated_primitive(
    "factorized_projected_q_bwd",
    FACTORIZED_BACKWARD,
    (Input.X.value, Input.SH.value, Input.W.value, 4, 5, 3),
    (0, 1, 2),
    dout_index=3,
)


def _dbwd_impl(
    x,
    sh,
    weights,
    dout,
    tx,
    tsh,
    tweights,
    tdout,
    senders,
    receivers,
    row_ptr,
    *,
    schedule,
    active,
):
    _validate(schedule, x, sh, weights, senders, receivers, row_ptr, dout)
    attributes = _generated_attrs(schedule, x.dtype, backward_jvp_active=active)
    shapes = tuple(jax.ShapeDtypeStruct(a.shape, a.dtype) for a in (x, sh, weights))
    operands = (x, sh, weights, senders, receivers, dout) + tuple(
        value
        for value, requested in zip((tx, tsh, tweights, tdout), active)
        if requested
    )
    return jax.ffi.ffi_call(FACTORIZED_TARGET, shapes)(
        *operands,
        operation=factorized_backward_jvp_operation(active),
        **attributes,
    )


def _dbwd_abstract(
    x,
    sh,
    weights,
    dout,
    tx,
    tsh,
    tweights,
    tdout,
    senders,
    receivers,
    row_ptr,
    *,
    schedule,
    active,
):
    _validate(schedule, x, sh, weights, senders, receivers, row_ptr, dout)
    for a, b, requested in zip(
        (x, sh, weights, dout), (tx, tsh, tweights, tdout), active
    ):
        if requested and (a.shape != b.shape or a.dtype != b.dtype):
            raise ValueError("tangent shape/dtype mismatch")
    return tuple(jax.core.ShapedArray(a.shape, a.dtype) for a in (x, sh, weights))


dbwd_p.def_impl(_dbwd_impl)
dbwd_p.def_abstract_eval(_dbwd_abstract)
_register_generated_lowering(
    dbwd_p,
    lambda params: (
        (Input.X.value, Input.SH.value, Input.W.value, 8, 9, 3)
        + tuple(4 + index for index, value in enumerate(params["active"]) if value)
    ),
    operation=lambda params: factorized_backward_jvp_operation(params["active"]),
    source_options=lambda params: {"backward_jvp_active": params["active"]},
)


def _fwd_jvp_impl(
    x, sh, weights, tx, tsh, tweights, senders, receivers, row_ptr, *, schedule, active
):
    if not any(active):
        return jnp.zeros((x.shape[0], schedule.output_dim), dtype=x.dtype)
    attributes = _generated_attrs(schedule, x.dtype, forward_jvp_active=active)
    shape = jax.ShapeDtypeStruct((x.shape[0], schedule.output_dim), x.dtype)
    operands = (x, sh, weights, senders, row_ptr) + tuple(
        value for value, requested in zip((tx, tsh, tweights), active) if requested
    )
    return jax.ffi.ffi_call(FACTORIZED_TARGET, shape)(
        *operands,
        operation=factorized_forward_jvp_operation(active),
        **attributes,
    )


def _fwd_jvp_abstract(
    x, sh, weights, tx, tsh, tweights, senders, receivers, row_ptr, *, schedule, active
):
    _validate(schedule, x, sh, weights, senders, receivers, row_ptr)
    return jax.core.ShapedArray((x.shape[0], schedule.output_dim), x.dtype)


fwd_jvp_p.def_impl(_fwd_jvp_impl)
fwd_jvp_p.def_abstract_eval(_fwd_jvp_abstract)
_register_generated_lowering(
    fwd_jvp_p,
    lambda params: (
        (Input.X.value, Input.SH.value, Input.W.value, 6, 8)
        + tuple(
            len(Input) + index for index, value in enumerate(params["active"]) if value
        )
    ),
    operation=lambda params: factorized_forward_jvp_operation(params["active"]),
    source_options=lambda params: {"forward_jvp_active": params["active"]},
)


def _fwd_jvp_rule(primals, tangents, *, schedule):
    x, sh, weights, senders, receivers, row_ptr = primals
    active = tuple(type(tangent) is not ad.Zero for tangent in tangents[:3])
    tx, tsh, tw = (
        _materialize_symbolic_zero(tangent)
        if is_active
        else jnp.zeros((), dtype=primal.dtype)
        for primal, tangent, is_active in zip((x, sh, weights), tangents[:3], active)
    )
    return (
        fwd_p.bind(*primals, schedule=schedule),
        fwd_jvp_p.bind(
            x,
            sh,
            weights,
            tx,
            tsh,
            tw,
            senders,
            receivers,
            row_ptr,
            schedule=schedule,
            active=active,
        ),
    )


ad.primitive_jvps[fwd_p] = _fwd_jvp_rule


def _fwd_jvp_jvp_rule(primals, tangents, *, schedule, active):
    """Differentiate the trilinear projected forward-JVP exactly.

    For trilinear ``F``, the first JVP is the sum of ``F(tx, sh, w)``,
    ``F(x, tsh, w)``, and ``F(x, sh, tw)``. Differentiating each of its three
    operands gives a 3-by-3 product rule of generated forward-JVP calls.
    """
    x, sh, weights, tx, tsh, tw, senders, receivers, row_ptr = primals
    dx, dsh, dw, dtx, dtsh, dtw, _, _, _ = tangents

    # ``active`` describes (tx, tsh, tw) in the inner JVP. ``q_active`` marks
    # outer derivatives of (x, sh, weights), while ``t_active`` marks outer
    # derivatives of those inner tangents. Classify them before materialising
    # zeros: inactive scalar placeholders must never reach a generated kernel.
    q_active = tuple(type(tangent) is not ad.Zero for tangent in (dx, dsh, dw))
    t_active = tuple(
        requested and type(tangent) is not ad.Zero
        for requested, tangent in zip(active, (dtx, dtsh, dtw))
    )
    zero_x, zero_sh, zero_w = (
        jnp.zeros_like(x),
        jnp.zeros_like(sh),
        jnp.zeros_like(weights),
    )
    tx = _materialize_symbolic_zero(tx) if active[0] else zero_x
    tsh = _materialize_symbolic_zero(tsh) if active[1] else zero_sh
    tw = _materialize_symbolic_zero(tw) if active[2] else zero_w
    dx = _materialize_symbolic_zero(dx) if q_active[0] else zero_x
    dsh = _materialize_symbolic_zero(dsh) if q_active[1] else zero_sh
    dw = _materialize_symbolic_zero(dw) if q_active[2] else zero_w
    dtx = _materialize_symbolic_zero(dtx) if t_active[0] else zero_x
    dtsh = _materialize_symbolic_zero(dtsh) if t_active[1] else zero_sh
    dtw = _materialize_symbolic_zero(dtw) if t_active[2] else zero_w

    # Rows select the tangent operand in the first JVP. Columns differentiate
    # one operand of that trilinear summand. Row-major order defines the
    # generated product-rule summand order.
    base_operands = (x, sh, weights)
    tangent_operands = (tx, tsh, tw)
    primal_directions = (dx, dsh, dw)
    tangent_directions = (dtx, dtsh, dtw)
    zero_directions = (zero_x, zero_sh, zero_w)
    product_rule = []
    for tangent_axis in range(3):
        values = list(base_operands)
        values[tangent_axis] = tangent_operands[tangent_axis]
        for derivative_axis in range(3):
            directions = list(zero_directions)
            if derivative_axis == tangent_axis:
                enabled = t_active[tangent_axis]
                directions[derivative_axis] = tangent_directions[derivative_axis]
            else:
                enabled = active[tangent_axis] and q_active[derivative_axis]
                directions[derivative_axis] = primal_directions[derivative_axis]
            term_active = tuple(axis == derivative_axis for axis in range(3))
            product_rule.append(
                (enabled, tuple(values), tuple(directions), term_active)
            )
    terms = [
        fwd_jvp_p.bind(
            *values,
            *directions,
            senders,
            receivers,
            row_ptr,
            schedule=schedule,
            active=term_active,
        )
        for enabled, values, directions, term_active in product_rule
        if enabled
    ]
    tangent = (
        sum(terms[1:], terms[0])
        if terms
        else jnp.zeros((x.shape[0], schedule.output_dim), dtype=x.dtype)
    )
    return (
        fwd_jvp_p.bind(
            x,
            sh,
            weights,
            tx,
            tsh,
            tw,
            senders,
            receivers,
            row_ptr,
            schedule=schedule,
            active=active,
        ),
        tangent,
    )


ad.primitive_jvps[fwd_jvp_p] = _fwd_jvp_jvp_rule


def _fwd_jvp_transpose(
    ct, x, sh, weights, tx, tsh, tw, senders, receivers, row_ptr, *, schedule, active
):
    if any(ad.is_undefined_primal(value) for value in (x, sh, weights)):
        raise NotImplementedError(
            "factorized_projected_fwd_jvp transpose requires defined coefficients"
        )
    undefined = tuple(ad.is_undefined_primal(value) for value in (tx, tsh, tw))
    if any(
        is_undefined and not requested
        for is_undefined, requested in zip(undefined, active)
    ):
        raise NotImplementedError(
            "inactive factorized_projected_fwd_jvp directions must be defined"
        )
    if type(ct) is ad.Zero:
        return (
            None,
            None,
            None,
            *(
                jnp.zeros_like(_materialize_symbolic_zero(value))
                if is_undefined
                else None
                for value, is_undefined in zip((tx, tsh, tw), undefined)
            ),
            None,
            None,
            None,
        )
    x, sh, weights, ct = map(_materialize_symbolic_zero, (x, sh, weights, ct))
    grads = bwd_p.bind(
        x, sh, weights, ct, senders, receivers, row_ptr, schedule=schedule
    )
    tangent_grads = tuple(
        grad if is_undefined else None for grad, is_undefined in zip(grads, undefined)
    )
    return (None, None, None, *tangent_grads, None, None, None)


ad.primitive_transposes[fwd_jvp_p] = _fwd_jvp_transpose


def _bwd_jvp_rule(primals, tangents, *, schedule):
    x, sh, weights, dout, senders, receivers, row_ptr = primals
    active = tuple(type(tangent) is not ad.Zero for tangent in tangents[:4])
    primal = bwd_p.bind(*primals, schedule=schedule)
    if not any(active):
        return primal, tuple(jnp.zeros_like(value) for value in primal)
    tx, tsh, tw, tdout = (
        _materialize_symbolic_zero(tangent)
        if is_active
        else jnp.zeros((), dtype=primal.dtype)
        for primal, tangent, is_active in zip(
            (x, sh, weights, dout), tangents[:4], active
        )
    )
    return (
        primal,
        dbwd_p.bind(
            x,
            sh,
            weights,
            dout,
            tx,
            tsh,
            tw,
            tdout,
            senders,
            receivers,
            row_ptr,
            schedule=schedule,
            active=active,
        ),
    )


ad.primitive_jvps[bwd_p] = _bwd_jvp_rule


def _bwd_transpose(
    cotangents, x, sh, weights, dout, senders, receivers, row_ptr, *, schedule
):
    """Transpose one differentiated input of the projected backward.

    This is the Hessian symmetry identity for ``B_q = grad_q <F, dout>``.
    Higher-order transforms only need one unknown primal at a time. Rejecting
    wider requests avoids pretending that an incomplete custom rule handles a
    general reverse sweep.
    """
    primals = (x, sh, weights, dout)
    undefined = tuple(ad.is_undefined_primal(value) for value in primals)
    if sum(undefined) != 1:
        raise NotImplementedError(
            "factorized_projected_q_bwd transpose requires one undefined primal"
        )
    active = tuple(type(value) is not ad.Zero for value in cotangents)
    if not any(active):
        zeros = tuple(
            jnp.zeros_like(_materialize_symbolic_zero(value)) for value in primals
        )
        return (
            *(zero if requested else None for zero, requested in zip(zeros, undefined)),
            None,
            None,
            None,
        )
    x, sh, weights, dout = map(_materialize_symbolic_zero, primals)
    cx, csh, cw = (
        _materialize_symbolic_zero(value)
        if requested
        else jnp.zeros((), dtype=primal.dtype)
        for value, primal, requested in zip(cotangents, (x, sh, weights), active)
    )
    q_grads = dbwd_p.bind(
        x,
        sh,
        weights,
        dout,
        cx,
        csh,
        cw,
        jnp.zeros_like(dout),
        senders,
        receivers,
        row_ptr,
        schedule=schedule,
        active=(*active, False),
    )
    dout_grad = fwd_jvp_p.bind(
        x,
        sh,
        weights,
        cx,
        csh,
        cw,
        senders,
        receivers,
        row_ptr,
        schedule=schedule,
        active=active,
    )
    grads = (*q_grads, dout_grad)
    return (
        *(grad if requested else None for grad, requested in zip(grads, undefined)),
        None,
        None,
        None,
    )


ad.primitive_transposes[bwd_p] = _bwd_transpose


def _dbwd_jvp_rule(primals, tangents, *, schedule, active):
    """Differentiate ``DB_q(z)[v]`` using its multilinear cross terms."""
    x, sh, weights, dout, tx, tsh, tw, tdout, senders, receivers, row_ptr = primals
    dx, dsh, dw, ddout, dtx, dtsh, dtw, dtdout, _, _, _ = tangents
    z = (x, sh, weights, dout)
    dz = (dx, dsh, dw, ddout)
    v = (tx, tsh, tw, tdout)
    dv = (dtx, dtsh, dtw, dtdout)
    z_active = tuple(type(tangent) is not ad.Zero for tangent in dz)
    dv_active = tuple(
        requested and type(tangent) is not ad.Zero
        for requested, tangent in zip(active, dv)
    )
    zero_v = tuple(jnp.zeros((), dtype=value.dtype) for value in z)
    primal = dbwd_p.bind(*primals, schedule=schedule, active=active)
    if any(dv_active):
        dv_term = dbwd_p.bind(
            x,
            sh,
            weights,
            dout,
            *(
                _materialize_symbolic_zero(tangent) if requested else zero
                for tangent, requested, zero in zip(dv, dv_active, zero_v)
            ),
            senders,
            receivers,
            row_ptr,
            schedule=schedule,
            active=dv_active,
        )
    else:
        dv_term = tuple(jnp.zeros_like(value) for value in primal)

    tangent = list(dv_term)
    for i, (zi, dzi) in enumerate(zip(z, dz)):
        if not z_active[i]:
            continue
        for j, vj in enumerate(v):
            if i == j or not active[j]:
                continue
            cross_inputs = list(z)
            cross_inputs[i] = _materialize_symbolic_zero(dzi)
            cross_inputs[j] = _materialize_symbolic_zero(vj)
            cross = bwd_p.bind(
                *cross_inputs, senders, receivers, row_ptr, schedule=schedule
            )
            for k, value in enumerate(cross):
                if k != i and k != j:
                    tangent[k] = tangent[k] + value
    return primal, tuple(tangent)


ad.primitive_jvps[dbwd_p] = _dbwd_jvp_rule


def _dbwd_transpose(
    cotangents,
    x,
    sh,
    weights,
    dout,
    tx,
    tsh,
    tweights,
    tdout,
    senders,
    receivers,
    row_ptr,
    *,
    schedule,
    active,
):
    """Transpose the mixed derivative using Hessian symmetry.

    The spatial backward is the gradient of ``vdot(F, dout)`` with respect
    to ``(x, sh, weights)``.  Its derivative is therefore symmetric in those
    three tangent slots.  The remaining ``dout`` cotangent is the forward JVP
    in the received cotangent direction.  This closes reverse-over-forward
    force-loss differentiation without a materialized reference expansion.
    """
    if any(ad.is_undefined_primal(value) for value in (x, sh, weights, dout)):
        raise NotImplementedError(
            "factorized_projected_q_dbwd transpose requires defined coefficients"
        )
    undefined = tuple(
        ad.is_undefined_primal(value) for value in (tx, tsh, tweights, tdout)
    )
    if any(
        is_undefined and not requested
        for is_undefined, requested in zip(undefined, active)
    ):
        raise NotImplementedError(
            "inactive factorized_projected_q_dbwd directions must be defined"
        )
    active_cotangents = tuple(type(value) is not ad.Zero for value in cotangents)
    if not any(active_cotangents):
        zeros = tuple(
            jnp.zeros_like(_materialize_symbolic_zero(value))
            for value in (tx, tsh, tweights, tdout)
        )
        return (
            None,
            None,
            None,
            None,
            *(zero if requested else None for zero, requested in zip(zeros, undefined)),
            None,
            None,
            None,
        )
    x, sh, weights, dout = map(_materialize_symbolic_zero, (x, sh, weights, dout))
    cx, csh, cw = (
        _materialize_symbolic_zero(value)
        if requested
        else jnp.zeros((), dtype=primal.dtype)
        for value, primal, requested in zip(
            cotangents, (x, sh, weights), active_cotangents
        )
    )
    zero_dout = jnp.zeros_like(dout)
    q_grads = dbwd_p.bind(
        x,
        sh,
        weights,
        dout,
        cx,
        csh,
        cw,
        zero_dout,
        senders,
        receivers,
        row_ptr,
        schedule=schedule,
        active=(*active_cotangents, False),
    )
    dout_grad = fwd_jvp_p.bind(
        x,
        sh,
        weights,
        cx,
        csh,
        cw,
        senders,
        receivers,
        row_ptr,
        schedule=schedule,
        active=active_cotangents,
    )
    tangent_grads = (q_grads[0], q_grads[1], q_grads[2], dout_grad)
    tangent_grads = tuple(
        value if is_undefined else None
        for value, is_undefined in zip(tangent_grads, undefined)
    )
    return (
        None,
        None,
        None,
        None,
        *tangent_grads,
        None,
        None,
        None,
    )


ad.primitive_transposes[dbwd_p] = _dbwd_transpose


# The generated kernels operate on one graph topology at a time.  These rules
# preserve that contract while allowing JAX to map feature and weight batches.
batching.primitive_batchers[fwd_p] = _batch_factorized(
    fwd_p, ("node", "edge", "edge"), ("node",)
)
batching.primitive_batchers[bwd_p] = _batch_factorized(
    bwd_p, ("node", "edge", "edge", "node"), ("node", "edge", "edge")
)
batching.primitive_batchers[dbwd_p] = _batch_factorized(
    dbwd_p,
    ("node", "edge", "edge", "node", "node", "edge", "edge", "node"),
    ("node", "edge", "edge"),
    tangent_start=4,
)
batching.primitive_batchers[fwd_jvp_p] = _batch_factorized(
    fwd_jvp_p,
    ("node", "edge", "edge", "node", "edge", "edge"),
    ("node",),
    tangent_start=3,
)


def factorized_projected(schedule, x, sh, weights, senders, receivers, row_ptr):
    return fwd_p.bind(x, sh, weights, senders, receivers, row_ptr, schedule=schedule)


__all__ = ["factorized_projected"]
