name: OEQ CUDA C++ Extension Build Verification

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
    types: [ labeled ]

permissions:
  contents: read

jobs:
  verify_cuda_extension:
    if: ${{ github.event.label.name == 'ci-ready' || github.event_name != 'pull_request' }}
    runs-on: ubuntu-24.04
    
    container: 
      image: nvcr.io/nvidia/cuda:12.9.0-devel-ubuntu24.04 # Pre installed CUDA toolkit
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: '**/requirements_cuda_ci.txt'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements_cuda_ci.txt
        pip install -e .

    - name: Test extension build via import 
      run: |
        pytest tests/import_test.py -k test_import